### ISSUE TITLE
Import Failure

### ISSUE THREAD

**Issue by Karuna2Karan** [Akouddane/EditableQuickViewForm#1]
The import of managed solution is failing without proper error.

![editableqview error](https://user-images.githubusercontent.com/54361970/81161979-22810000-8f95-11ea-9b57-9f94cfe10d08.png)

**Comment by umerjaved** [comment]
I am facing the same issue

**Comment by Akouddane** [comment]
Hello,

Try to increase maximum file size under Settings > Administration > System settings > Email Tab > Maximum file size (15000)

I'll release tonight a lighter new version (1.0.0.2) that meets the default value of this setting.

![image](https://user-images.githubusercontent.com/20278132/81196582-86b8b980-8fbf-11ea-87ad-33fbc90309df.png)

Thanks,
Amine

**Comment by Akouddane** [comment]
version 1.0.0.2 released :)

**Comment by Karuna2Karan** [comment]
Hi Akouddane,

Thanks for the updated solution. I was able to install the new solution successfully. However, I'm facing issue configuring the control. 
1. Adding the control to source Lookup Field.
2. Pasted the Quick View Form ID
![image](https://user-images.githubusercontent.com/54361970/81348028-fc0eb200-90c5-11ea-9cf2-67efa494dbb4.png)

After save and publish, getting error loading control in the form. 
Error occured during initialization of control: EasyCrmEQVF.EditableQuickViewForm;Message: Value should be of type: guid: Parameter Name: id

It would be nice if you couldn't put a short config guide document here.

**Comment by Akouddane** [comment]
Hi Karuna2Karan,

I see the quick form id is not valid, try with removing the first "3d" in your configuration string value: 
29DE27BC-A257-...
Please, let me know if if works

I'll add a specific error when the guid is not valid in next version

Thanks,
Amine
